version: '3'

services:
  db:
    container_name: ecommerce_db
    build: app/db/.
    ports:
      - 3306:3306
    env_file:
      - app/db/db.env
    networks:
      - project

  app:
    container_name: ecommerce_app
    build: app/web/.
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - project

networks:
  project:
  name: project